package com.csye6225.fall2018.courseservice.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Course")
public class Course {
	private String Id;
	private String courseId;
	private String professorId;
	private String taId;
	private String department;
	private String boardId;
	private List<String> listOfRegisteredStudents;
	
	
	
	public Course() {
		
	}



	public Course(String Id, String courseId, String professorId, String taId, String department, String boardId,
			List<String> listOfRegisteredStudents) {
		super();
		this.Id = Id;
		this.courseId = courseId;
		this.professorId = professorId;
		this.taId = taId;
		this.department = department;
		this.boardId = boardId;
		this.listOfRegisteredStudents = listOfRegisteredStudents;
	}



	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")
	public String getId() {
        return Id;
	}
	public void setId(String Id) {
        this.Id = Id;
	}


	@DynamoDBIndexHashKey(attributeName="courseId", globalSecondaryIndexName = "courseIdIndex")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}


	@DynamoDBAttribute(attributeName="professorId")
	public String getProfessorId() {
		return professorId;
	}
	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}


	@DynamoDBAttribute(attributeName="taId")
	public String getTaId() {
		return taId;
	}
	public void setTaId(String taId) {
		this.taId = taId;
	}


	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}


	@DynamoDBAttribute(attributeName="boardId")
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}


	@DynamoDBAttribute(attributeName="listOfRegisteredStudents")
	public List<String> getListOfRegisteredStudents() {
		return listOfRegisteredStudents;
	}
	public void setListOfRegisteredStudents(List<String> listOfRegisteredStudents) {
		this.listOfRegisteredStudents = listOfRegisteredStudents;
	}

    
	
	
	
	
}
