package com.csye6225.fall2018.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Registrar")
public class Registrar {
	private String Id;
	private String RegistrationId;
	private String OfferingId;
	private String OfferingType;
	private String Department; 
	private double PerUnitPrice;
	
	public Registrar() {
		
	}
	
	public Registrar(String Id, String registrationId, String offeringId, String offeringType, String department,
			double perUnitPrice) {
		super();
		this.Id = Id;
		this.RegistrationId = registrationId;
		this.OfferingId = offeringId;
		this.OfferingType = offeringType;
		this.Department = department;
		this.PerUnitPrice = perUnitPrice;
	}
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")
	public String getId() {
		return Id;
	}
	public void setId(String id) {
		Id = id;
	}
	
	@DynamoDBIndexHashKey(attributeName="RegistrationId", globalSecondaryIndexName = "registrationIdIndex")
	public String getRegistrationId() {
		return RegistrationId;
	}
	public void setRegistrationId(String registrationId) {
		RegistrationId = registrationId;
	}
	
	@DynamoDBAttribute(attributeName="OfferingId")
	public String getOfferingId() {
		return OfferingId;
	}
	public void setOfferingId(String offeringId) {
		OfferingId = offeringId;
	}
	
	@DynamoDBAttribute(attributeName="OfferingType")
	public String getOfferingType() {
		return OfferingType;
	}
	public void setOfferingType(String offeringType) {
		OfferingType = offeringType;
	}
	
	@DynamoDBAttribute(attributeName="Department")
	public String getDepartment() {
		return Department;
	}
	public void setDepartment(String department) {
		Department = department;
	}
	
	@DynamoDBAttribute(attributeName="PerUnitPrice")
	public double getPerUnitPrice() {
		return PerUnitPrice;
	}
	public void setPerUnitPrice(double perUnitPrice) {
		PerUnitPrice = perUnitPrice;
	}

	
	
	
}
